apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ldap-account-manager.fullname" . }}-env
  labels:
    {{- include "ldap-account-manager.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.extraEnv }}
  {{ $k }}: {{ $v | toString | b64enc | quote }}
  {{- end }}

---

{{- if .Values.usePrivateRegistry }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ldap-account-manager.fullname" . }}-creds
  labels:
    {{- include "ldap-account-manager.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
